logging:
  level: DEBUG

sentence_transformer:
  model_name: all-MiniLM-L6-v2

vectorization:
  environment: eu-west4-gcp
  metric: euclidean

situation_analysis:
  model_name: gpt-3.5-turbo
  temperature: 0.0
  verbose: False
